name: redecom_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.0.3
  jwt_decode: ^0.3.1
  image_picker: ^1.1.2
  geolocator: ^11.0.0
  image: 3.2.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  socket_io_client: ^2.0.3+1
  http: ^0.13.0
  intl: 0.19.0
  google_maps_flutter: ^2.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/icon/
